### ISSUE TITLE
Executable name

### ISSUE THREAD

**Issue by moodmosaic** [GreanTech/Qaiain#23]
Currently, the executable name is _HandleMessages_. Perhaps a more appropriate name would be one of the following:
- Qaiain
- Qaiain.CommandLine

However, the assembly name containing the unit tests is named _Grean.Qaiain.UnitTests_ so I think the following names are more consistent:
- Grean.Qaiain
- Grean.Qaiain.CommandLine

**Comment by ploeh** [comment]
The reason I named the executable _HandleMessages_ is exactly because it's a command-line executable. When you're on the command-line, it makes more sense to have to write

```
> HandleMessages
```

than

```
> Qaiain
```

or something similar.

Particularly if you want to use the command in a script, the imperative name of the executable reads better (in my subjective opinion) than `Qaiain` or `Qaiain.CommandLine`, which doesn't communicate what the command _does_.

So, it's by design :)

**Comment by moodmosaic** [comment]
Alright, then :)
